storage: ./storage
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  "@agentive-ui/*":
    access: $all
    publish: $all
    unpublish: $all
  "@*/*":
    access: $all
    publish: $authenticated
    proxy: npmjs
  "**":
    access: $all
    publish: $authenticated
    proxy: npmjs
logs:
  - { type: stdout, format: pretty, level: warn }
